### PR TITLE
fix: Reduce the scroll debounce timeout to 100ms and update only if offset changes

### LINKED ISSUE #3175: Offsets not updating correctly when embedded in scrollable website
https://youtu.be/QyXFw99aPnI

Offsets seem to not be updated immediately when the parent screen is scrolled. It will be updated when actions are done on the canvas.

### PR DESCRIPTION
**Pull request by ad1992**
fixes #3175 
This can go into the patch version release along with #3174 
try it out [here](https://3scmb.csb.app/)

### CODE REVIEW

File: src/components/App.tsx [hunk 1]
```diff
@@ -1008,7 +1008,14 @@ class App extends React.Component<ExcalidrawProps, AppState> {
...
   private onScroll = debounce(() => {
-    this.setState({ ...this.getCanvasOffsets() });
+    const { offsetTop, offsetLeft } = this.getCanvasOffsets();
+    if (
+      this.state.offsetLeft === offsetLeft &&
+      this.state.offsetTop === offsetTop
+    ) {
+      return;
+    }
+    this.setState({ offsetTop, offsetLeft });
```
Comment (dwelle) [inline src/components/App.tsx:1018]:
```suggestion
    this.setState(state => {
      if (
        state.offsetLeft === offsetLeft &&
        state.offsetTop === offsetTop
      ) {
        return null;
      }
      return { offsetTop, offsetLeft }
    });
```

**Review by dwelle — APPROVED** [review]
