### PR TITLE
Remove last get/setTransform

### LINKED ISSUE #861: Firefox ESR doesn't support `context.getTransform`
### Stack trace

```
m.getTransform is not a function:

getTransform (renderer/renderScene.ts:47:42)
componentDidUpdate (index.tsx:2301:37)
p.focus&&p.focus();for (../node_modules/react-dom/cjs/react-dom.production.min.js:251:462)
unstable_runWithPriority (../node_modules/scheduler/cjs/scheduler.production.min.js:18:436)
dg (../node_modules/react-dom/cjs/react-dom.production.min.js:120:324)
Xj (../node_modules/react-dom/cjs/react-dom.production.min.js:244:436)
Lj (../node_modules/react-dom/cjs/react-dom.production.min.js:223:419)
ig (../node_modules/react-dom/cjs/react-dom.production.min.js:121:114)
unstable_runWithPriority (../node_modules/scheduler/cjs/scheduler.production.min.js:18:436)
dg (../node_modules/react-dom/cjs/react-dom.production.min.js:120:324)
ig (../node_modules/react-dom/cjs/react-dom.production.min.js:121:60)
dg (../node_modules/react-dom/cjs/react-dom.production.min.js:120:495)
Rg (../node_modules/react-dom/cjs/react-dom.production.min.js:214:155)
isMounted (../node_modules/react-dom/cjs/react-dom.production.min.js:133:236)
setState (../node_modules/react/cjs/react.production.min.js:13:230)
syncActionResult (index.tsx:704:11)
json=([0-9]+), (index.tsx:774:13)
tryCatch (../node_modules/regenerator-runtime/runtime.js:45:39)
context.dispatchException (../node_modules/regenerator-runtime/runtime.js:271:21)
function (../node_modules/regenerator-runtime/runtime.js:97:20)
asyncGeneratorStep (../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:24)
_next (../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:8)
```

### localStorage

```
{"i18nextLng":"en"}
```

### PR DESCRIPTION
**Pull request by vjeux**
My original hack to put the scale when we create the canvas element doesn't make much sense. It should be done when we are rendering the scene. I moved it there in this PR.

The rest was all about forwarding the scale to where it's needed.

Fixes #861

### CODE REVIEW

File: src/renderer/renderElement.ts [hunk 1]
```diff
@@ -64,6 +64,10 @@ function generateElementCanvas(
   const rc = rough.canvas(canvas);
   drawElementOnCanvas(element, rc, context);
   context.translate(-CANVAS_PADDING, -CANVAS_PADDING);
+  context.scale(
+    1 / (window.devicePixelRatio * zoom),
+    1 / (window.devicePixelRatio * zoom),
+  );
```
Comment (vjeux) [inline src/renderer/renderElement.ts]: This isn't technically needed since we never draw on that canvas afterwards but let's make sure we reset the transform anyway so it doesn't bite us in the future.
