### PR TITLE
fix: rotate the text element when binding to a rotated container

### LINKED ISSUE #6476: rotated container renders unrotated text
related https://github.com/excalidraw/excalidraw/issues/5858

excal-bug-rotated-container-text

### PR DESCRIPTION
**Pull request by siddhant1**
Fixes #6476

### CODE REVIEW

File: src/element/textWysiwyg.tsx [hunk 1]
```diff
@@ -590,6 +590,7 @@ export const textWysiwyg = ({
           ),
         });
       }
+
```
Comment (ad1992) [inline src/element/textWysiwyg.tsx:593]:
```suggestion
```

**Review by ad1992 — APPROVED** [review]

**Comment by ad1992** [comment]
@siddhant1 thanks again. merging 🚀
