### PR TITLE
fix: Use Array.from when spreading over set so that typescript transpiles correctly in the umd build

### LINKED ISSUE #3164: Binding arrows is broken in excalidraw package
Steps to reproduce
1. Go to https://ehlz3.csb.app/ and draw any shape
2. Draw an arrow and try to bind it to the shape
3. Breaks the build, throws 👇 error and as a result the pointer also doesn't get restored.

Screenshot 2021-03-03 at 3 34 05 PM

### PR DESCRIPTION
**Pull request by ad1992**
fixes #3164 
fixes https://github.com/excalidraw/excalidraw/issues/3153
[spreadArrays](https://www.typescriptlang.org/docs/handbook/release-notes/overview.html#more-accurate-array-spread) introduced in 3.6 only supports arrays by default. We can enable the flag `downlevelIteration` to make it work with other types but it increases bundle size by `~20kb`which is unnecessary so using `Array.from` instead.

Try it out [here](https://y0ld3.csb.app/)
TODOS

- [x] update changelog
- [x] Release patch version

### CODE REVIEW

**Comment by dwelle** [comment]
fixes https://github.com/excalidraw/excalidraw/issues/3153

File: src/element/binding.ts [hunk 1]
```diff
@@ -183,7 +183,9 @@ const bindLinearElement = (
   });
   mutateElement(hoveredElement, {
     boundElementIds: [
-      ...new Set([...(hoveredElement.boundElementIds ?? []), linearElement.id]),
+      ...Array.from(
+        new Set([...(hoveredElement.boundElementIds ?? []), linearElement.id]),
+      ),
     ],
```
Comment (dwelle) [inline src/element/binding.ts:189]: let's assign the `Array.from` directly to `boundElementIds` to save some CPU (can't suggest commit FSR)

**Review by lipis — APPROVED** [review]

**Review by dwelle — APPROVED** [review]

**Review by dwelle — APPROVED** [review]
