### PR TITLE
Normalize dimensions

### LINKED ISSUE #505: Perfect resizing with shift button is broken for flipped elements
Jan-22-2020 00-14-04

### PR DESCRIPTION
**Pull request by dwelle**
fixes #505

I decided to do another take on normalizing dimensions, because fixing #505 without it would be a pain. On top of it, I still believe that not-normalizing will result (and already has) in lots of lost time, and hacks on top of hacks. Without it, we need to account for negative dimensions (`width`/`height`), handles reported e.g. as `w` when in reality user holds `e` etc.

This PR doesn't yet normalize `arrow` & `line` elem. It works without it, but we should normalize every element. Will fix tomorrow or in another PR.

Note: while functioning, I'm not sure if it doesn't break unrelated things. Also, tomorrow I plan to refactor the codebase to remove the hacks which are no longer necessary.

(I haven't in fact checked #342, so not sure what I'm doing differently, and what I haven't thought of. Will check tomorrow, too.)

:warning: 2nd commit adds dimensions to the left panel for debugging. The commit must be removed before merge. But it can technically be tightened up and reused for #517 (but as of now it's not styled, and has terrible perf).

In the GIF below notice that `width`/`height` dimensions are no longer ever negative.

excalidraw_normalize_dimensions

### CODE REVIEW

**Comment by lipis** [comment]
Looks good!

**Comment by dwelle** [comment]
I'll actually withhold touching arrows/lines until #338 is done because it'd only cause issues.

**Comment by dwelle** [comment]
Alright. Ready for review.

Changes from previous:

1. now also normalizing during creation of new element (also after `mouseUp` which is technically unnecessary, but just to be sure)
2. Changed how dimensions/position is computed during creation. There are non-trivial handling due to not handling linear elements ATM (`text`, `line`). Will rewrite after #338 lands.

The debug commit is now removed, so ready for merge. To preview with the debug info, use this: https://excalidraw-c5t2q6wnt.now.sh/

**Comment by dwelle** [comment]
(force pushed to fix commit message)

**Comment by lipis** [comment]
Don't forget to remove the debug boxes.. before merging.

**Comment by dwelle** [comment]
Already removed as mentioned.

**Comment by lipis** [comment]
Works nice with arrows as well..

**Comment by dwelle** [comment]
Actually, I don't touch arrows at all. Which you can check: excalidraw-c5t2q6wnt.now.sh -- the dimensions of arrows/lines can still be negative.

**Comment by dwelle** [comment]
Mhmm.. just noticed there's a regression in proportial resize (`shift`) of arrows/lines. Worked a while ago.

Need to fix before merge.

**Comment by dwelle** [comment]
Fixed.

**Comment by lipis** [comment]
Ship it...! 🐑

**Comment by dwelle** [comment]
I'd let @vjeux weigh in because he had some strong opinions on the last normalization take :).

**Comment by vjeux** [comment]
Go for it if you made it work :)

**Comment by lipis** [comment]
🍻

File: src/utils.ts [hunk 1]
```diff
@@ -86,3 +86,7 @@ export function removeSelection() {
     selection.removeAllRanges();
   }
 }
+
+export function distance(x: number, y: number) {
+  return Math.abs(x > y ? x - y : y - x);
+}
```
Comment (pshihn) [inline src/utils.ts]: This is a redundant check. 
`Math.abs(x-y)` is all you need

Comment (dwelle) [reply src/utils.ts]: :blush: will commit a refactor in a bit

Comment (dwelle) [reply src/utils.ts]: But I reckon instead of that, I'll keep the expression, and remove the `Math.abs` --- for perf?

Dunno how I ended doing both.

Comment (pshihn) [reply src/utils.ts]: Don't think this sorta little perf really matters :)
