### PR TITLE
fix: hide text align for labelled arrows

### LINKED ISSUE #6316: Text alignment of Arrow doesn't work.
Text alignment of Arrow doesn't work below. It depends on the width of textbox.

Screenshot 2023-03-05 at 19 12 43

### PR DESCRIPTION
**Pull request by ad1992**
`Text align` is not really useful for labelled arrows hence I am proposing to hide it instead.
fixes #6316

### CODE REVIEW

File: src/element/textElement.ts [hunk 1]
```diff
@@ -673,6 +673,29 @@ export const shouldAllowVerticalAlign = (
...
+      }
+      return true;
+    }
+    const boundTextElement = getBoundTextElement(element);
+    if (boundTextElement) {
+      if (isArrowElement(element)) {
+        return false;
+      }
+      return true;
+    }
```
Comment (dwelle) [inline src/element/textElement.ts:694]: what is this for? Seems same as the check above it.

Comment (ad1992) [reply src/element/textElement.ts]: since we fetch selected Elements including the bound text (https://github.com/excalidraw/excalidraw/blob/master/src/scene/selection.ts#L81) hence this block can be removed

**Review by dwelle — APPROVED** [review]
