### PR TITLE
fix: Show Windows share icon for Windows users

### LINKED ISSUE #3259: Add support for Windows share experience
More details on this https://blogs.windows.com/windowsdeveloper/2017/04/06/new-share-experience-windows-10-creators-update/

### PR DESCRIPTION
**Pull request by h7y**
## Preview:
Preview

## Closes
#3259

### CODE REVIEW

**Review by tomayac — APPROVED** [review]
LGTM, approval

Thank you `<3`

File: src/excalidraw-app/collab/RoomDialog.tsx [hunk 1]
```diff
@@ -31,8 +32,20 @@ const RoomDialog = ({
   setErrorMessage: (message: string) => void;
 }) => {
   const roomLinkInput = useRef<HTMLInputElement>(null);
-  const navigator = window.navigator as any;
-  const isAppleBrowser = /Apple/.test(navigator.vendor);
+
+  const getShareIcon = () => {
```
Comment (ad1992) [inline src/excalidraw-app/collab/RoomDialog.tsx:36]: since it is a pure function lets keep it outside`RoomDialog`  so its not recreated (new reference) for every rerender.

Comment (tomayac) [reply src/excalidraw-app/collab/RoomDialog.tsx:36]: Oh, right, good catch, @ad1992!

**Review by ad1992 — APPROVED** [review]
