### PR TITLE
Fix: refreshing the page while selecting saves the selection element

### LINKED ISSUE #591: refreshing the page while selecting saves the selection element.

### PR DESCRIPTION
**Pull request by lissitz**
Fixes #591.

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -1494,7 +1494,7 @@ export class App extends React.Component<any, AppState> {
   }
 
   private saveDebounced = debounce(() => {
-    saveToLocalStorage(elements, this.state);
+    saveToLocalStorage(elements.filter(x => x.type !== "selection"), this.state);
```
Comment (vjeux) [inline src/index.tsx]: Looks like it doesn't pass lint. Could you run prettier by any chance?

Comment (dwelle) [reply src/index.tsx]: Weird that CSB didn't trigger the prettier.

**Comment by dwelle** [comment]
Thx!
