### PR TITLE
fix: load fonts for `exportToCanvas`

### LINKED ISSUE #8296: export to blob does not load new fonts
Export to blob outside the editor (`exportToCanvas`), does not load new fonts, as the fonts are not loaded by the `FontFace` API. This does not affect SVG export (as the fonts are fetched manually), nor PNG export inside the editor (as by coincidence fonts are already loaded by the editor), but it does affect `links.excalidraw.com`.

In the following screenshot, we should see `Excalifont`, but instead we see a fallback font.

Screenshot 2024-07-30 at 0 00 00

### PR DESCRIPTION
**Pull request by Mrazator**
Closes #8296

### CODE REVIEW

File: packages/excalidraw/scene/export.ts [hunk 1]
```diff
@@ -187,7 +187,13 @@ export const exportToCanvas = async (
     canvas.height = height * appState.exportScale;
     return { canvas, scale: appState.exportScale };
   },
+  loadFonts: () => Promise<void> = async () => {
+    await Fonts.load(elements);
+  },
```
Comment (dwelle) [inline packages/excalidraw/scene/export.ts:192]: is this so we can override for utils export?

File: packages/excalidraw/fonts/index.ts [hunk 2]
```diff
@@ -44,10 +48,19 @@ export class Fonts {
...
+    // lazy load the font registration
     if (!Fonts._registered) {
-      // lazy load the fonts
       Fonts._registered = Fonts.init();
+    } else if (!Fonts._initialized) {
+      // case when host app register fonts before they are lazy loaded
+      // don't override whatever has been previously registered
+      Fonts._registered = new Map([
+        ...Fonts.init().entries(),
+        ...Fonts._registered.entries(),
```
Comment (dwelle) [inline packages/excalidraw/fonts/index.ts:62]: is this in anticipation for registering custom fonts in runtime? Otherwise `Fonts.init().entries()` already gives you all the fonts anyway

Comment (Mrazator) [reply packages/excalidraw/fonts/index.ts:62]: yup, preparation for custom fonts

File: packages/excalidraw/fonts/index.ts [hunk 3]
```diff
@@ -119,7 +138,28 @@ export class Fonts {
     }
   };
 
-  public load = async () => {
+  /**
+   * Load font faces for a given scene and trigger scene update.
+   */
+  public load = async (): Promise<FontFace[]> => {
```
Comment (dwelle) [inline packages/excalidraw/fonts/index.ts:144]: rename to `loadSceneFonts()`?

File: packages/excalidraw/fonts/index.ts [hunk 4]
```diff
@@ -119,7 +138,28 @@ export class Fonts {
...
+    const loaded = await Fonts.loadFontFaces(this.sceneFamilies);
+    this.onLoaded(loaded);
+    return loaded;
+  };
+
+  /**
+   * Load font faces for passed elements - use when the scene is unavailable (i.e. export).
+   */
+  public static load = async (
```
Comment (dwelle) [inline packages/excalidraw/fonts/index.ts:153]: `preloadFontsForElements`?

Comment (Mrazator) [reply packages/excalidraw/fonts/index.ts:153]: `loadFontsForElements`?

**Review by dwelle — APPROVED** [review]
