### PR TITLE
fix: Preview image is being stretched when the proportions are wrong

### LINKED ISSUE #490: Preview image is being stretched when the proportions are wrong
Screenshot 2020-01-21 at 12 44 59 PM

https://excalidraw.com/?id=5681150794137600

### PR DESCRIPTION
**Pull request by lissitz**
Fixes #490. Preserves the ratio of the preview image when width / height reaches max-width/max-height.

### CODE REVIEW

**Comment by lipis** [comment]
https://deploy-preview-503--excalidraw.netlify.com/?id=5681150794137600

File: src/scene/getExportCanvasPreview.ts [hunk 1]
```diff
@@ -21,8 +21,11 @@ export function getExportCanvasPreview(
     height
   ) {
     const tempCanvas = document.createElement("canvas");
-    tempCanvas.style.width = width + "px";
-    tempCanvas.style.height = height + "px";
+    if(width > height) {
+      tempCanvas.style.width = width + "px";
+    } else {
+      tempCanvas.style.height = height + "px";
```
Comment (lipis) [inline src/scene/getExportCanvasPreview.ts]:
```suggestion
      tempCanvas.style.height = `${height}px`;
```

File: src/scene/getExportCanvasPreview.ts [hunk 2]
```diff
@@ -21,8 +21,11 @@ export function getExportCanvasPreview(
     height
   ) {
     const tempCanvas = document.createElement("canvas");
-    tempCanvas.style.width = width + "px";
-    tempCanvas.style.height = height + "px";
+    if(width > height) {
+      tempCanvas.style.width = width + "px";
```
Comment (lipis) [inline src/scene/getExportCanvasPreview.ts]:
```suggestion
      tempCanvas.style.width = `${width}px`;
```
