### PR TITLE
fix: Elbow end point disconnect

### LINKED ISSUE #10642: elbow arrow binding detached on segment move
Image

### PR DESCRIPTION
**Pull request by mtolmacs**
Closes #10642

### CODE REVIEW

File: packages/excalidraw/actions/actionFinalize.tsx [hunk 1]
```diff
@@ -82,7 +82,10 @@ export const actionFinalize = register<FormData>({
         app.scene,
       );
 
-      if (isBindingElement(element)) {
+      if (
+        isBindingElement(element) &&
+        !appState.selectedLinearElement.segmentMidPointHoveredCoords
+      ) {
```
Comment (dwelle) [inline packages/excalidraw/actions/actionFinalize.tsx:88]: not really sure what's going on here tbh, but let's do it :)
