### PR TITLE
Fix many syncing issues

### LINKED ISSUE #946: Remote pointer sometimes doesn't show
No clue how to repro. Just refresh a tab to regenerate a user. Sometimes that user doesn't have a pointer (in the other tab) for the whole session (the scene syncs normally).

Will need to investigate code.

### PR DESCRIPTION
**Pull request by petehunt**
* move to using an `isDeleted` field on the element rather than `deletedIds`. this simplified a bunch of the code as we can use the same reconciliation algorithm for every type of modification.
* fix undo to propagate changes to other peers. reset the undo stack when we receive an update from someone else. this behavior is still surprising, and it's possible to lose your redo stack mid-operation if someone else makes a change.
* fix issue where cursors would get lost sometimes
* show real-time resizing of elements

fixes #946 and some of #937

### CODE REVIEW

File: src/components/App.tsx [hunk 1]
```diff
@@ -342,41 +318,53 @@ export class App extends React.Component<any, AppState> {
...
+                    } else if (
+                      localElementMap.hasOwnProperty(element.id) &&
+                      localElementMap[element.id].version === element.version &&
+                      localElementMap[element.id].versionNonce !==
+                        element.versionNonce
+                    ) {
+                      // resolve conflicting edits deterministically by taking the one with the lowest versionNonce
+                      if (
+                        localElementMap[element.id].versionNonce <
+                        element.versionNonce
```
Comment (vjeux) [inline src/components/App.tsx]: Interesting approach!

File: src/element/index.ts [hunk 2]
```diff
@@ -24,3 +27,27 @@ export {
...
+      acc[element.id] = element;
+      return acc;
+    },
+    {},
+  );
+}
+
+export function getDrawingVersion(elements: readonly ExcalidrawElement[]) {
+  return elements.reduce((acc, el) => acc + el.version, 0);
+}
```
Comment (vjeux) [inline src/element/index.ts]: This is nifty

File: src/element/index.ts [hunk 3]
```diff
@@ -24,3 +27,27 @@ export {
...
+
+export function countNonDeletedElements(
```
Comment (vjeux) [inline src/element/index.ts]: You only use this to check if there is at least one non deleted element. You could rename to hasNonDeletedElements and use .some() to it short circuits when the first one matches.

File: src/components/App.tsx [hunk 4]
```diff
@@ -342,41 +318,53 @@ export class App extends React.Component<any, AppState> {
...
                   // add local elements that weren't deleted or on remote
                   .concat(...Object.values(localElementMap));
               }
-              this.setState({
-                deletedIds,
-              });
+              this.lastBroadcastedOrReceivedSceneVersion = getDrawingVersion(
+                elements,
+              );
+              history.clear();
```
Comment (vjeux) [inline src/components/App.tsx]: can you add a comment explaining why you clear the history? :)

File: src/components/App.tsx [hunk 5]
```diff
@@ -1586,6 +1568,7 @@ export class App extends React.Component<any, AppState> {
         p1[0] += deltaX;
         p1[1] += deltaY;
       }
+      mutateElement(element);
```
Comment (vjeux) [inline src/components/App.tsx]: Were you too lazy to refactor the code to move the mutation in the second arg? Or is it the way the code is intended to be written?

File: src/components/App.tsx [hunk 6]
```diff
@@ -2263,13 +2249,20 @@ export class App extends React.Component<any, AppState> {
...
     if (this.state.scrolledOutside !== scrolledOutside) {
       this.setState({ scrolledOutside: scrolledOutside });
     }
     this.saveDebounced();
-    if (history.isRecording()) {
+
+    if (
+      getDrawingVersion(elements) > this.lastBroadcastedOrReceivedSceneVersion
+    ) {
       this.broadcastSceneUpdate();
```
Comment (vjeux) [inline src/components/App.tsx]: Nice, so it's going to broadcast on every mouse move!

File: src/data/restore.ts [hunk 7]
```diff
@@ -52,7 +52,7 @@ export function restore(
 
       return {
         ...element,
-        version: element.version || 0,
+        version: element.version || 1,
```
Comment (vjeux) [inline src/data/restore.ts]: So the sum will count the number of elements I assume :)

File: src/element/index.ts [hunk 8]
```diff
@@ -24,3 +27,27 @@ export {
   normalizeDimensions,
 } from "./sizeHelpers";
 export { showSelectedShapeActions } from "./showSelectedShapeActions";
+
+export function getSyncableElements(elements: readonly ExcalidrawElement[]) {
+  return elements.filter(el => !isInvisiblySmallElement(el));
```
Comment (vjeux) [inline src/element/index.ts]: What's the rationale for not syncing those?

File: src/components/App.tsx (hunk 5 above)
Comment (petehunt) [reply src/components/App.tsx]: yes, i fixed this is in a follow up PR that i'll put up after this is merged.
