### PR TITLE
fix: Two finger panning is slow

### LINKED ISSUE #2497: Firefox scrolling is slow
Firefox `wheel` event deltas are really tiny in comparison to other browsers.

For example, in Chrome on my mouse, `deltaY` is `166`, whereas in Firefox it is `5`.

Known, WONTFIX issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1057252

(via https://twitter.com/midned/status/1336717295004037123)

### PR DESCRIPTION
**Pull request by zsviczian**
fix #2497
fix https://github.com/excalidraw/excalidraw/issues/6913

With this change, two finger panning on iPad matches the single finger panning with the hand tool. I tested this with various zoom levels.

sorry - can't figure out how to update tests to accommodate the change :(

### CODE REVIEW

File: packages/excalidraw/components/App.tsx [hunk 1]
```diff
@@ -5097,8 +5097,8 @@ class App extends React.Component<AppProps, AppState> {
 
         this.translateCanvas({
           zoom: zoomState.zoom,
-          scrollX: zoomState.scrollX + deltaX / nextZoom,
-          scrollY: zoomState.scrollY + deltaY / nextZoom,
+          scrollX: zoomState.scrollX + 2 * (deltaX / nextZoom),
+          scrollY: zoomState.scrollY + 2 * (deltaY / nextZoom),
```
Comment (dwelle) [inline packages/excalidraw/components/App.tsx:5101]: why 2x? Isn't this more related to `devicePixelRatio` which on most mobile touchscreens would coincide with `2`?

**Comment by dwelle** [comment]
Yeah, I was just wondering if there was a reasoning behind it, or it's just a magic number. I'll add a comment it's a magic number then. :)

File: packages/excalidraw/components/App.tsx (hunk 1 above)
Comment (dwelle) [inline packages/excalidraw/components/App.tsx:5101]:
```suggestion
          // 2x multiplier is just a magic number that makes this work correctly
          // on touchscreen devices (note: if we get report that panning is slower/faster
          // than actual movement, consider swapping with devicePixelRatio)
          scrollX: zoomState.scrollX + 2 * (deltaX / nextZoom),
          scrollY: zoomState.scrollY + 2 * (deltaY / nextZoom),
```

**Review by dwelle — APPROVED** [review]

**Comment by dwelle** [comment]
Thanks Zsolt! ❤️
