### PR TITLE
fix(editor): Hardened fixed point and bound element parsing in restore

### LINKED ISSUE #10812: getGlobalFixedPointForBindableElement exception when fixedPointRatio is null
@mtolmacs 

I am getting this error/warning on some of my older drawings:

Image

The issue is here `const [fixedX, fixedY] = normalizeFixedPoint(fixedPointRatio);`

```ts
export const getGlobalFixedPointForBindableElement = (
  fixedPointRatio: FixedPoint,
  element: ExcalidrawBindableElement,
  elementsMap: ElementsMap,
): GlobalPoint => {
  const [fixedX, fixedY] = normalizeFixedPoint(fixedPointRatio);

  return pointRotateRads(
    pointFrom(
      element.x + element.width * fixedX,
      element.y + element.height * fixedY,
    ),
    elementCenterPoint(element, elementsMap),
    element.angle,
  );
```

However, normalizeFixPoint may return null value:
```ts
export const normalizeFixedPoint = <T extends FixedPoint | null>(
  fixedPoint: T,
): T extends null ? null : FixedPoint
```

the error trickles from repairBinding in restore.ts, when the arrow is bound to a start or end point, but for some reason, fixedPoint was null (I did not investigate why or how).

```ts
    // migrating legacy focus point bindings
    if (boundElement && elementsMap) {
      const p = LinearElementEditor.getPointAtIndexGlobalCoordinates(
        element,
        startOrEnd === "start" ? 0 : element.points.length - 1,
        elementsMap,
      );
      const mode = isPointInElement(p, boundElement, elementsMap)
        ? "inside"
        : "orbit";
      const focusPoint =
        mode === "inside"
          ? p
          : projectFixedPointOntoDiagonal(
              element,
              p,
              boundElement,
              startOrEnd,
              elementsMap,
              { value: 1 as NormalizedZoomValue },
            ) || p;
```

### PR DESCRIPTION
**Pull request by mtolmacs**
Should fix #10812

### CODE REVIEW

File: packages/element/src/binding.ts [hunk 1]
```diff
@@ -2447,21 +2447,32 @@ export const getArrowLocalFixedPoints = (
...
 };
 
-export const normalizeFixedPoint = <T extends FixedPoint | null>(
+export const isFixedPoint = (
+  fixedPoint: any,
+): fixedPoint is FixedPointBinding["fixedPoint"] => {
+  return (
+    Array.isArray(fixedPoint) &&
+    fixedPoint.length === 2 &&
+    fixedPoint.every((coord) => typeof coord === "number")
```
Comment (dwelle) [inline packages/element/src/binding.ts]:
```suggestion
    fixedPoint.every((coord) => coord && typeof coord === "number")
```
to guard against NaN if we're already doing it this granularly

File: packages/element/src/binding.ts [hunk 2]
```diff
@@ -2447,21 +2447,32 @@ export const getArrowLocalFixedPoints = (
...
+  );
+};
+
+export const normalizeFixedPoint = <T extends FixedPoint>(
   fixedPoint: T,
-): T extends null ? null : FixedPoint => {
+): FixedPoint => {
+  const point: FixedPoint = isFixedPoint(fixedPoint)
+    ? fixedPoint
+    : [0.5001, 0.5001];
```
Comment (dwelle) [inline packages/element/src/binding.ts]: not quite related to this fix, but - the `0.5001` defaults will always be detected as below our `0.001` threshold (`0.5001 - 0.5 < 0.0001` resolves as true) so the default fixed point will never settle into a stable state. Let's change the comparison check to < 0.0001?

File: packages/excalidraw/data/restore.ts [hunk 3]
```diff
@@ -155,7 +156,9 @@ const repairBinding = <T extends ExcalidrawArrowElement>(
         | ExcalidrawElbowArrowElement["startBinding"]
         | ExcalidrawElbowArrowElement["endBinding"] = {
         ...binding,
-        fixedPoint: normalizeFixedPoint(binding.fixedPoint ?? [0, 0]),
+        fixedPoint: normalizeFixedPoint(
+          isFixedPoint(binding.fixedPoint) ? binding.fixedPoint : [0, 0],
```
Comment (dwelle) [inline packages/excalidraw/data/restore.ts]: if we're already checking `isFixedPoint` inside the `normalizeFixedPoint` then we can keep `normalizeFixedPoint(binding.fixedPoint ?? [0, 0])`

File: packages/excalidraw/data/restore.ts [hunk 4]
```diff
@@ -199,7 +204,7 @@ const repairBinding = <T extends ExcalidrawArrowElement>(
       : existingElementsMap;
 
     // migrating legacy focus point bindings
-    if (boundElement && elementsMap) {
+    if (typeof boundElement !== "undefined" && boundElement && elementsMap) {
```
Comment (dwelle) [inline packages/excalidraw/data/restore.ts]: redundant typeof check

Comment (mtolmacs) [reply packages/excalidraw/data/restore.ts]: Yet the original error claimed that boundElement is not defined. The original guard should've stopped it if this would be redundant. Any ideas?

Comment (dwelle) [reply packages/excalidraw/data/restore.ts]: dunno, but `boundElement &&` guards against undefined by default so this is a voodoo check :)

@zsviczian are you sure you're on latest? Your stack trace points to restore.ts:124 which leads to somewhere else, if the source maps work correctly.

File: packages/element/src/binding.ts (hunk 1 above)
Comment (mtolmacs) [reply packages/element/src/binding.ts]: Not sure how your check is not superfluous. `typeof null === "number"` is false, `typeof undefined === "number"` is still false, `typeof anythingnotanumber === "number"` still false.

File: packages/excalidraw/data/restore.ts (hunk 4 above)
Comment (zsviczian) [reply packages/excalidraw/data/restore.ts]: My stack trace is irrelevant. It is from my fork and the Obsidian build.

File: packages/element/src/binding.ts (hunk 2 above)
Comment (mtolmacs) [reply packages/element/src/binding.ts]: The code flow wasn't really clear anyway, so I rewrote it. Good catch, missed it completely.

File: packages/excalidraw/data/restore.ts (hunk 3 above)
Comment (mtolmacs) [reply packages/excalidraw/data/restore.ts]: Good catch, removed.

File: packages/excalidraw/data/restore.ts (hunk 4 above)
Comment (mtolmacs) [reply packages/excalidraw/data/restore.ts]: Okay, the boundElement undefined might be unrelated then. I'll remove the voodoo.

File: packages/element/src/binding.ts (hunk 1 above)
Comment (dwelle) [reply packages/element/src/binding.ts]: `typeof NaN === "number"` so the `!!coord` guards against that

Comment (dwelle) [reply packages/element/src/binding.ts]: we might wanna add as `isNumber()` or `isFinite()` util at this point since we check this a couple times in the codebase

Comment (mtolmacs) [reply packages/element/src/binding.ts]: > `typeof NaN === "number"` so the `!!coord` guards against that

> we might wanna add as `isNumber()` or `isFinite()` util at this point since we check this a couple times in the codebase

So why not just use `Number.isFinite()` as the only call, which cover all of this (except boxed numbers, i.e. `new Number(0.5)` but that shouldn't be an issue).
