### PR TITLE
fix: image-mirroring in export preview and in exported svg

### LINKED ISSUE #4850: The preview doesn't respect horizontally flipped images
Repro:
* Insert an image
* Right click / flip horizontally
* The view on excalidraw works fine
* Click on the export to image icon
* The view doesn't show the image flipped
* Click copy to clipboard, it doesn't have the image flipped either

### PR DESCRIPTION
**Pull request by ryan-di**
Instead of trying to figure out how to combine scaling, translation, and rotation in svg, we first flip the image itself if needed. This solves the problem at hand : )

fix #4850

### CODE REVIEW

**Review by ad1992 — APPROVED** [review]
Sweet ❤️
lets wait for @dwelle before merging

**Comment by ad1992** [comment]
@ryan-di can we add a spec for this ?

File: src/renderer/renderElement.ts [hunk 1]
```diff
@@ -964,6 +969,8 @@ export const renderElementToSvg = (
           image.setAttribute("width", "100%");
           image.setAttribute("height", "100%");
           image.setAttribute("href", fileData.dataURL);
+          image.style.transform =
+            element.scale[0] === -1 ? `translateX(${width}px) scaleX(-1)` : "";
```
Comment (dwelle) [inline src/renderer/renderElement.ts:973]: applying on the image would flip all instances of the image since the idea behind this is having just a single image element per image instance on canvas for file size reasons

Comment (ryan-di) [reply src/renderer/renderElement.ts]: good catch 👍

**Review by dwelle — APPROVED** [review]

**Comment by dwelle** [comment]
🚀
