### PR TITLE
fix some element types reset to selection when the lock is active

### LINKED ISSUE #745: Some element types reset to selection even if the lock is active
Arrow, line and text elements reset the shape selector to selection after using them when the lock is active.

### PR DESCRIPTION
**Pull request by lissitz**
fixes #745

### CODE REVIEW

File: src/actions/actionFinalize.tsx [hunk 1]
```diff
@@ -20,11 +21,16 @@ export const actionFinalize: Action = {
...
+      resetCursor();
+    }
     return {
       elements: newElements,
       appState: {
         ...appState,
-        elementType: "selection",
+        elementType: appState.elementLocked
+          ? appState.elementType
+          : "selection",
```
Comment (dwelle) [inline src/actions/actionFinalize.tsx]: We actually keep this behavior even if element is locked. `Esc` in this case should reset to selection no matter what.

Comment (dwelle) [reply src/actions/actionFinalize.tsx]: Except, when in `multiElement` mode. In that case, it should just finalize the shape.

File: src/actions/actionFinalize.tsx [hunk 2]
```diff
@@ -20,11 +21,16 @@ export const actionFinalize: Action = {
       }
       appState.multiElement.shape = null;
     }
+    if (!appState.elementLocked) {
```
Comment (dwelle) [inline src/actions/actionFinalize.tsx]:
```suggestion
    if (!appState.elementLocked || !appState.multiElement) {
```

File: src/actions/actionFinalize.tsx [hunk 3]
```diff
@@ -20,11 +21,16 @@ export const actionFinalize: Action = {
...
+      resetCursor();
+    }
     return {
       elements: newElements,
       appState: {
         ...appState,
-        elementType: "selection",
+        elementType: appState.elementLocked
```
Comment (dwelle) [inline src/actions/actionFinalize.tsx]:
```suggestion
        elementType: appState.elementLocked && appState.multiElement
```

Note, this one will require reruning prettier after applying this change

File: src/utils.ts [hunk 4]
```diff
@@ -126,3 +126,7 @@ export function distance2d(x1: number, y1: number, x2: number, y2: number) {
   const yd = y2 - y1;
   return Math.sqrt(xd * xd + yd * yd);
 }
+
+export function resetCursor() {
+  document.documentElement.style.cursor = "";
+}
```
Comment (dwelle) [inline src/utils.ts]: Since you've moved this, I propose moving `setCursorForShape` from `index.tsx` here, too.

File: src/index.tsx [hunk 5]
```diff
@@ -1065,10 +1061,17 @@ export class App extends React.Component<any, AppState> {
...
+                  resetCursor();
+                  this.setState({
+                    editingElement: element,
+                    elementType: "selection",
+                  });
+                } else {
+                  this.setState({
+                    editingElement: element,
+                  });
+                }
```
Comment (dwelle) [inline src/index.tsx]: This one actually causes a UX regression: when you have locked shapes, and create a text element, clicking away to finalize the text creates a new one.

Comment (dwelle) [reply src/index.tsx]: I've fixed this in https://github.com/excalidraw/excalidraw/pull/746/commits/f157e419a7f3876d61374caf7d09f39cb330663b

File: src/actions/actionFinalize.tsx (hunk 1 above)
Comment (dwelle) [reply src/actions/actionFinalize.tsx]: fixed in https://github.com/excalidraw/excalidraw/pull/746/commits/12d5d9b704d0b297c88c7366e9a35806cdf147b6

File: src/utils.ts (hunk 4 above)
Comment (dwelle) [reply src/utils.ts]: ...or never mind, too much work (it's coupled to other things). Let's leave it for later.

**Comment by dwelle** [comment]
Alright, let's ship this. Thanks!
