### PR TITLE
fix: add random tiny offsets to avoid linear elements from being clipped

### LINKED ISSUE #5585: round edges of linear elements disappear
At the end of the video all points are aligned to the grid:

https://user-images.githubusercontent.com/45559664/185178466-31bcae4b-782f-458c-a6bd-81680a3bacfa.mp4

Shapes:
```json
{"type":"excalidraw/clipboard","elements":[{"type":"line","version":1233,"versionNonce":1630602581,"isDeleted":false,"id":"9tF9H_amkO-t6n5hMPyQC","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,"x":-2720,"y":-5920,"strokeColor":"#000000","backgroundColor":"transparent","width":248,"height":120,"seed":11578965,"groupIds":[],"strokeSharpness":"round","boundElements":[],"updated":1660752424920,"link":null,"locked":false,"startBinding":null,"endBinding":null,"lastCommittedPoint":null,"startArrowhead":null,"endArrowhead":null,"points":[[0,0],[248,-11.111111111111313],[248,108.88888888888869],[0,100]]},{"type":"line","version":1505,"versionNonce":1246520955,"isDeleted":false,"id":"Si6T4w2MMC_9ZX-7AyRrk","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,"x":-2754.379310344828,"y":-5779.708657467998,"strokeColor":"#000000","backgroundColor":"transparent","width":205.62068965517224,"height":187.00656628733572,"seed":1151856789,"groupIds":[],"strokeSharpness":"round","boundElements":[],"updated":1660752424920,"link":null,"locked":false,"startBinding":null,"endBinding":null,"lastCommittedPoint":null,"startArrowhead":null,"endArrowhead":null,"points":[[0,0],[-205.62068965517224,26.71522375533368],[-205.62068965517224,-160.29134253200203],[0,-160.29134253200203],[0,26.71522375533368]]}],"files":{}}
```

### PR DESCRIPTION
**Pull request by ryan-di**
closes #5585

### CODE REVIEW

File: src/element/bounds.ts [hunk 1]
```diff
@@ -200,6 +214,7 @@ const getMinMaxXYFromCurvePathOps = (
     },
     { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity },
   );
+  // console.log([minX, minY, maxX, maxY], ops);
```
Comment (dwelle) [inline src/element/bounds.ts:217]:
```suggestion
```

File: src/element/bounds.ts [hunk 2]
```diff
@@ -152,6 +152,10 @@ const getCubicBezierCurveBound = (
   return [minX, minY, maxX, maxY];
 };
 
+const getRandomOffset = () => {
+  return Math.random() / 1_000_000;
```
Comment (dwelle) [inline src/element/bounds.ts:156]:
```suggestion
  return Math.random() / 1000000;
```

https://caniuse.com/mdn-javascript_grammar_numeric_separators isn't "universally" supported yet

**Review by dwelle — APPROVED** [review]
