### PR TITLE
fix: don't crash on drop highlighted text onto canvas

### LINKED ISSUE #3971: Drag and drop from outside excalidraw throws unfriendly error
Dragging and dropping a non-excalidraw object onto the canvas leads to a non-user friendly message `Cannot read properties of undefined (reading 'type')`.

I understand why we get this (we're not expected to be dragging other objects into the canvas), but suggest that the error message should be something nice like 'This object cannot be added to the Excalidraw canvas.'

See below for reproduction (Ubuntu 20.04, Chromium 93.0.4577.63):

excalidraw drag drop error

---

This feels simple enough for a first contribution, I will try and take a look this weekend.

### PR DESCRIPTION
**Pull request by tommilligan**
Closes #3971 

Adds a missing check for if a file is present on drop. This is required manually due a typescript `as any` cast further inside the code block. Also manually adds a couple of type annotations to make clear that file may not be provided.

The behaviour is now to take no action, if a file is not found (rather than showing an error modal).

excalidraw-no-crash-on-drop-text

### CODE REVIEW

File: src/components/App.tsx [hunk 1]
```diff
@@ -5008,7 +5008,7 @@ class App extends React.Component<AppProps, AppState> {
       return;
     }
 
-    const file = event.dataTransfer?.files[0];
+    const file: File | undefined = event.dataTransfer?.files[0];
```
Comment (dwelle) [inline src/components/App.tsx:5011]:
```suggestion
    const file = event.dataTransfer?.files.item(0);
```

File: src/components/App.tsx [hunk 2]
```diff
@@ -4932,7 +4932,7 @@ class App extends React.Component<AppProps, AppState> {
 
   private handleAppOnDrop = async (event: React.DragEvent<HTMLDivElement>) => {
     try {
-      const file = event.dataTransfer.files[0];
+      const file: File | undefined = event.dataTransfer.files[0];
```
Comment (dwelle) [inline src/components/App.tsx:4935]:
```suggestion
      const file = event.dataTransfer.files.item(0);
```

File: src/components/App.tsx (hunk 1 above)
Comment (dwelle) [reply src/components/App.tsx:5011]: Doing `: File | undefined` is one of the rare cases where type declaration is less typesafe than doing a type assertion `as File | undefined`, because TS will narrow down the assignment as `File` since it's inferred as such.

But, I've changed it to using `.item()` API instead which has the correct type we need.

File: src/packages/excalidraw/CHANGELOG.md [hunk 3]
```diff
@@ -67,6 +67,7 @@ Please add the latest change on the top under the correct section.
 
 ### Fixes
 
+- Fix raising an error when dragging and dropping some items without files onto the canvas [#4890](https://github.com/excalidraw/excalidraw/pull/4890).
```
Comment (dwelle) [inline src/packages/excalidraw/CHANGELOG.md:70]: I think we don't need a changelog for this as the changelog should be reserved for package-affecting changes (/cc @ad1992). But if we did, then we would have to put it under "Unreleased" section.

Comment (tommilligan) [reply src/packages/excalidraw/CHANGELOG.md:70]: :facepalm: agreed - sorry, I searched for `Fixes` and pasted in the first section I found, my mistake. Will remove in any case as you suggest

**Comment by tommilligan** [comment]
Thanks for the fast feedback - updated and squashed with your feedback (as it's such a small change)

**Comment by dwelle** [comment]
Thanks for the fix! ❤️

**Review by dwelle — APPROVED** [review]

**Comment by tommilligan** [comment]
> Thanks for the fix! heart

No problem, and thanks for the fast turnaround and maintaining such a great tool for everyone!
