### PR TITLE
fix: Make help toggle tabbable

### LINKED ISSUE #3287: Help toggle is not tabbable
Screenshot 2021-03-20 at 8 28 08 PM

I was thinking about changing it into a button. Is there any reason for it to be a `div`?

### PR DESCRIPTION
**Pull request by h7y**
Screenshot 2021-03-22 at 11 37 30 PM

## Fixes
#3287

### CODE REVIEW

File: src/components/HelpIcon.tsx [hunk 1]
```diff
@@ -9,7 +9,13 @@ type HelpIconProps = {
...
-    <div onClick={props.onClick}>{questionCircle}</div>
-  </label>
+  <button
+    className="help-icon"
+    onClick={props.onClick}
+    type="button"
+    title={`${props.title} — ?`}
+    aria-label={props.title}
+  >
+    <div aria-hidden="true">{questionCircle}</div>
```
Comment (ad1992) [inline src/components/HelpIcon.tsx:19]:
```suggestion
    {questionCircle}
```
Do we need this extra div ?

Comment (h7y) [reply src/components/HelpIcon.tsx:19]: Since the SVG doesn't have any label, I'm using the `div` to pass `aria-hidden="true"` similar to what's being done in `ToolButton.tsx`.

Comment (ad1992) [reply src/components/HelpIcon.tsx:19]: the svg itself has `aria-hidden` true so then this shouldn't be needed. We might have missed this in `ToolButton.tsx`.

**Review by ad1992 — APPROVED** [review]
