### PR TITLE
fix: use excal id so every element has unique id 

### LINKED ISSUE #3683: Every element must have unique id
Noticed this in the standalone component:

Screenshot 2021-05-30 at 23 21 45

This means you can't render two of them without id clashes.

### PR DESCRIPTION
**Pull request by ad1992**
Remove id where it wasn't needed
fixes #3683

### CODE REVIEW

File: src/components/App.tsx [hunk 1]
```diff
@@ -394,7 +393,10 @@ class App extends React.Component<AppProps, AppState> {
         }
       >
         <ExcalidrawContainerContext.Provider
-          value={this.excalidrawContainerRef.current}
+          value={{
+            container: this.excalidrawContainerRef.current,
+            id: this.id,
+          }}
```
Comment (dwelle) [inline src/components/App.tsx:399]: this will mess up referential integrity, thus rerender consumers unnecessarily, am I correct? And it looks like most of the UI is subscribing to this context.

If so, I'd suggest either 1) splitting into two context providers, or 2) factor the object out and update it only if either of the two values change.

File: src/css/styles.scss [hunk 2]
```diff
@@ -51,9 +51,7 @@
     image-rendering: -moz-crisp-edges; // FF
 
     z-index: var(--zIndex-canvas);
-  }
 
-  #canvas {
```
Comment (dwelle) [inline src/css/styles.scss:56]: we still need to distinguish the main canvas from any other canvas because we don't want the `position: absolute` to e.g. target the canvas in image export dialog

File: src/components/App.tsx (hunk 1 above)
Comment (ad1992) [reply src/components/App.tsx:399]: > this will mess up referential integrity, thus rerender consumers unnecessarily, am I correct? And it looks like most of the UI is subscribing to this context.

When do you think that will happen? The `id` is initialized only once in the constructor and would remain the same throughout the lifecycle of the comp...

File: src/css/styles.scss (hunk 2 above)
Comment (ad1992) [reply src/css/styles.scss:56]: good point , now I remember breaking it earlier 🤦🏻

File: src/components/App.tsx (hunk 1 above)
Comment (dwelle) [reply src/components/App.tsx:399]: I meant the value object `{}` the attributes are in (a new object will be created on every render). `Context.Provider` should be doing a simple equality check: https://reactjs.org/docs/context.html#contextprovider

File: src/css/styles.scss (hunk 2 above)
Comment (dwelle) [reply src/css/styles.scss:56]: haha, I thought it was me :)

Comment (ad1992) [reply src/css/styles.scss:56]: I broke it when introducing position absolute and you fixed it :)

File: src/components/App.tsx [hunk 3]
```diff
@@ -349,6 +359,7 @@ class App extends React.Component<AppProps, AppState> {
     }
     return (
       <canvas
+        className="excalidraw__canvas"
```
Comment (dwelle) [inline src/components/App.tsx:362]: Don't we want to start using BEM from now on?

File: src/components/App.tsx [hunk 4]
```diff
@@ -301,6 +305,11 @@ class App extends React.Component<AppProps, AppState> {
       }
       readyPromise.resolve(api);
     }
+
+    this.excalidrawContainerValue = {
+      container: this.excalidrawContainerRef.current,
```
Comment (dwelle) [inline src/components/App.tsx:310]: haven't checked: isn't this `null` when `constructor` runs?

File: src/components/App.tsx (hunk 3 above)
Comment (ad1992) [reply src/components/App.tsx:362]: that's why I named it `excalidraw__canvas` => `block__element`, what do you suggest ?

File: src/components/App.tsx (hunk 4 above)
Comment (ad1992) [reply src/components/App.tsx:310]: yeah my bad,  good catch 👍🏻

File: src/components/App.tsx (hunk 3 above)
Comment (dwelle) [reply src/components/App.tsx:363]: Okay, I think my BEM game isn't strong. I thought it only uses dashes :).

**Review by dwelle — APPROVED** [review]
